-- SIGESCOM - Paso 02
-- Ejecutar conectado como ADMINBD.
-- Crea el modelo base del Laboratorio 11 y lo extiende para el Proyecto Final.

-- DEPARTAMENTOS:
-- Catalogo de areas de la empresa, por ejemplo Tecnologia, Contabilidad o Recursos Humanos.
-- Los usuarios y las solicitudes quedan asociados a un departamento.
CREATE TABLE departamentos (
    id_departamento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR2(100) NOT NULL,
    estado          VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    fecha_creacion  DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_departamentos_nombre UNIQUE (nombre),
    CONSTRAINT ck_departamentos_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

-- ROLES:
-- Catalogo de permisos generales del sistema.
-- Define si un usuario actua como ADMIN, SOLICITANTE, APROBADOR o AUDITOR.
CREATE TABLE roles (
    id_rol         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol     VARCHAR2(30) NOT NULL,
    descripcion    VARCHAR2(200),
    estado         VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    fecha_creacion DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_roles_nombre UNIQUE (nombre_rol),
    CONSTRAINT ck_roles_estado CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT ck_roles_nombre CHECK (nombre_rol IN ('ADMIN', 'SOLICITANTE', 'APROBADOR', 'AUDITOR'))
);

-- USUARIOS:
-- Guarda los datos de acceso y perfil de cada persona que usa SIGESCOM.
-- Incluye correo, password en formato hash, departamento, puesto y estado de la cuenta.
CREATE TABLE usuarios (
    id_usuario          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo     VARCHAR2(150) NOT NULL,
    correo              VARCHAR2(150) NOT NULL,
    password_hash       VARCHAR2(300) NOT NULL,
    id_departamento     NUMBER NOT NULL,
    telefono            VARCHAR2(25),
    puesto              VARCHAR2(100) NOT NULL,
    estado              VARCHAR2(30) DEFAULT 'PENDIENTE_ACTIVACION' NOT NULL,
    intentos_fallidos   NUMBER DEFAULT 0 NOT NULL,
    bloqueado_hasta     DATE,
    ultimo_login        DATE,
    fecha_creacion      DATE DEFAULT SYSDATE NOT NULL,
    fecha_actualizacion DATE,
    CONSTRAINT uq_usuarios_correo UNIQUE (correo),
    CONSTRAINT fk_usuarios_departamento FOREIGN KEY (id_departamento) REFERENCES departamentos(id_departamento),
    CONSTRAINT ck_usuarios_estado CHECK (estado IN ('PENDIENTE_ACTIVACION', 'ACTIVO', 'INACTIVO', 'BLOQUEADO')),
    CONSTRAINT ck_usuarios_intentos CHECK (intentos_fallidos >= 0),
    CONSTRAINT ck_usuarios_correo CHECK (correo LIKE '%@%.%')
);

-- USUARIO_ROL:
-- Tabla intermedia para asignar uno o varios roles a un usuario.
-- Ejemplo: Maria puede ser SOLICITANTE y tambien APROBADOR.
CREATE TABLE usuario_rol (
    id_usuario_rol  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario      NUMBER NOT NULL,
    id_rol          NUMBER NOT NULL,
    estado          VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    fecha_asignacion DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_usuario_rol_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_usuario_rol_rol FOREIGN KEY (id_rol) REFERENCES roles(id_rol),
    CONSTRAINT uq_usuario_rol UNIQUE (id_usuario, id_rol),
    CONSTRAINT ck_usuario_rol_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

-- RESET_PASSWORD:
-- Guarda los codigos temporales usados para recuperar o cambiar la contrasena.
-- Cada codigo tiene fecha de expiracion y marca si ya fue usado.
CREATE TABLE reset_password (
    id_reset             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario           NUMBER NOT NULL,
    codigo_reset         VARCHAR2(100) NOT NULL,
    fecha_solicitud      DATE DEFAULT SYSDATE NOT NULL,
    fecha_expiracion     DATE NOT NULL,
    fecha_uso            DATE,
    usado                CHAR(1) DEFAULT 'N' NOT NULL,
    ip_solicitud         VARCHAR2(50),
    user_agent           VARCHAR2(300),
    intentos_validacion  NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT fk_reset_password_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT uq_reset_password_codigo UNIQUE (codigo_reset),
    CONSTRAINT ck_reset_password_usado CHECK (usado IN ('S', 'N')),
    CONSTRAINT ck_reset_password_fechas CHECK (fecha_expiracion > fecha_solicitud),
    CONSTRAINT ck_reset_password_intentos CHECK (intentos_validacion >= 0)
);

-- ESTADOS_SOLICITUD:
-- Catalogo del flujo de una solicitud de compra.
-- Ejemplo: BORRADOR, PENDIENTE, APROBADA, RECHAZADA o DEVUELTA.
CREATE TABLE estados_solicitud (
    id_estado      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo         VARCHAR2(30) NOT NULL,
    nombre         VARCHAR2(80) NOT NULL,
    estado         VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    orden_flujo    NUMBER NOT NULL,
    CONSTRAINT uq_estados_solicitud_codigo UNIQUE (codigo),
    CONSTRAINT ck_estados_solicitud_estado CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT ck_estados_solicitud_codigo CHECK (codigo IN ('BORRADOR', 'PENDIENTE', 'APROBADA', 'RECHAZADA', 'DEVUELTA', 'CANCELADA'))
);

-- PARAMETROS_SISTEMA:
-- Guarda valores configurables del sistema sin cambiar codigo PL/SQL.
-- Ejemplo: porcentaje de impuesto o monto minimo para aprobacion especial.
CREATE TABLE parametros_sistema (
    id_parametro    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR2(60) NOT NULL,
    valor_numero    NUMBER(14, 4),
    valor_texto     VARCHAR2(300),
    descripcion     VARCHAR2(300),
    fecha_creacion  DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_parametros_sistema_codigo UNIQUE (codigo)
);

-- SOLICITUDES:
-- Encabezado principal de una solicitud de compra.
-- Aqui se guarda quien solicita, departamento, prioridad, justificacion, estado y totales.
CREATE TABLE solicitudes (
    id_solicitud                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_solicitud                VARCHAR2(30) NOT NULL,
    id_usuario_solicitante          NUMBER NOT NULL,
    id_departamento                 NUMBER NOT NULL,
    id_estado                       NUMBER NOT NULL,
    prioridad                       VARCHAR2(20) NOT NULL,
    justificacion                   VARCHAR2(1000) NOT NULL,
    observaciones                   VARCHAR2(1000),
    subtotal                        NUMBER(14, 2) DEFAULT 0 NOT NULL,
    impuesto                        NUMBER(14, 2) DEFAULT 0 NOT NULL,
    total                           NUMBER(14, 2) DEFAULT 0 NOT NULL,
    requiere_aprobacion_especial    CHAR(1) DEFAULT 'N' NOT NULL,
    fecha_solicitud                 DATE DEFAULT SYSDATE NOT NULL,
    fecha_envio                     DATE,
    fecha_cierre                    DATE,
    fecha_actualizacion             DATE,
    CONSTRAINT uq_solicitudes_numero UNIQUE (numero_solicitud),
    CONSTRAINT fk_solicitudes_usuario FOREIGN KEY (id_usuario_solicitante) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_solicitudes_departamento FOREIGN KEY (id_departamento) REFERENCES departamentos(id_departamento),
    CONSTRAINT fk_solicitudes_estado FOREIGN KEY (id_estado) REFERENCES estados_solicitud(id_estado),
    CONSTRAINT ck_solicitudes_prioridad CHECK (prioridad IN ('BAJA', 'MEDIA', 'ALTA', 'URGENTE')),
    CONSTRAINT ck_solicitudes_especial CHECK (requiere_aprobacion_especial IN ('S', 'N')),
    CONSTRAINT ck_solicitudes_montos CHECK (subtotal >= 0 AND impuesto >= 0 AND total >= 0)
);

-- SOLICITUD_DETALLE:
-- Lineas o items de cada solicitud de compra.
-- Cada registro representa un producto o servicio solicitado, con cantidad y precio estimado.
CREATE TABLE solicitud_detalle (
    id_detalle          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitud        NUMBER NOT NULL,
    tipo_item           VARCHAR2(20) NOT NULL,
    descripcion         VARCHAR2(500) NOT NULL,
    cantidad            NUMBER(12, 2) NOT NULL,
    precio_estimado     NUMBER(14, 2) NOT NULL,
    proveedor_sugerido  VARCHAR2(200),
    subtotal_linea      NUMBER(14, 2) GENERATED ALWAYS AS (cantidad * precio_estimado) VIRTUAL,
    CONSTRAINT fk_detalle_solicitud FOREIGN KEY (id_solicitud) REFERENCES solicitudes(id_solicitud),
    CONSTRAINT ck_detalle_tipo CHECK (tipo_item IN ('PRODUCTO', 'SERVICIO')),
    CONSTRAINT ck_detalle_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_detalle_precio CHECK (precio_estimado > 0)
);

-- HISTORIAL_SOLICITUD:
-- Registro de trazabilidad de cambios de estado de una solicitud.
-- Guarda quien hizo la accion, estado anterior, estado nuevo, fecha y observacion.
CREATE TABLE historial_solicitud (
    id_historial       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitud       NUMBER NOT NULL,
    id_usuario_accion  NUMBER NOT NULL,
    estado_anterior    VARCHAR2(30),
    estado_nuevo       VARCHAR2(30) NOT NULL,
    observacion        VARCHAR2(1000) NOT NULL,
    fecha_accion       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_historial_solicitud FOREIGN KEY (id_solicitud) REFERENCES solicitudes(id_solicitud),
    CONSTRAINT fk_historial_usuario FOREIGN KEY (id_usuario_accion) REFERENCES usuarios(id_usuario)
);

-- BITACORA_USUARIOS:
-- Auditoria automatica sobre usuarios.
-- Los triggers insertan aqui cuando se registra un usuario o se cambia su contrasena.
CREATE TABLE bitacora_usuarios (
    id_bitacora      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario       NUMBER,
    correo           VARCHAR2(150),
    accion           VARCHAR2(50),
    descripcion      VARCHAR2(300),
    fecha_registro   DATE DEFAULT SYSDATE
);

-- BITACORA_SOLICITUDES:
-- Auditoria automatica sobre solicitudes.
-- Los triggers insertan aqui cuando se crea una solicitud o cambia de estado.
CREATE TABLE bitacora_solicitudes (
    id_bitacora       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitud      NUMBER,
    numero_solicitud  VARCHAR2(30),
    accion            VARCHAR2(50) NOT NULL,
    estado_anterior   VARCHAR2(30),
    estado_nuevo      VARCHAR2(30),
    descripcion       VARCHAR2(500),
    fecha_registro    DATE DEFAULT SYSDATE NOT NULL
);

-- LOG_API:
-- Registro general de operaciones importantes ejecutadas desde los endpoints REST.
-- Sirve para evidenciar acciones como login, registro, logout o eliminacion de borradores.
CREATE TABLE log_api (
    id_log          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modulo          VARCHAR2(50) NOT NULL,
    endpoint        VARCHAR2(120),
    metodo          VARCHAR2(10),
    id_usuario      NUMBER,
    resultado       VARCHAR2(20) NOT NULL,
    mensaje         VARCHAR2(1000),
    fecha_registro  DATE DEFAULT SYSDATE NOT NULL
);

INSERT INTO departamentos (nombre) VALUES ('Tecnologia');
INSERT INTO departamentos (nombre) VALUES ('Contabilidad');
INSERT INTO departamentos (nombre) VALUES ('Recursos Humanos');
INSERT INTO departamentos (nombre) VALUES ('Compras');
INSERT INTO departamentos (nombre) VALUES ('Gerencia');

INSERT INTO roles (nombre_rol, descripcion) VALUES ('ADMIN', 'Administra el sistema');
INSERT INTO roles (nombre_rol, descripcion) VALUES ('SOLICITANTE', 'Crea solicitudes');
INSERT INTO roles (nombre_rol, descripcion) VALUES ('APROBADOR', 'Aprueba solicitudes');
INSERT INTO roles (nombre_rol, descripcion) VALUES ('AUDITOR', 'Consulta informacion e historial');

INSERT INTO estados_solicitud (codigo, nombre, orden_flujo) VALUES ('BORRADOR', 'Borrador', 1);
INSERT INTO estados_solicitud (codigo, nombre, orden_flujo) VALUES ('PENDIENTE', 'Pendiente de aprobacion', 2);
INSERT INTO estados_solicitud (codigo, nombre, orden_flujo) VALUES ('APROBADA', 'Aprobada', 3);
INSERT INTO estados_solicitud (codigo, nombre, orden_flujo) VALUES ('RECHAZADA', 'Rechazada', 4);
INSERT INTO estados_solicitud (codigo, nombre, orden_flujo) VALUES ('DEVUELTA', 'Devuelta para correccion', 5);
INSERT INTO estados_solicitud (codigo, nombre, orden_flujo) VALUES ('CANCELADA', 'Cancelada', 6);

INSERT INTO parametros_sistema (codigo, valor_numero, descripcion)
VALUES ('IMPUESTO_VENTAS', 0.13, 'Porcentaje de impuesto usado para calcular solicitudes');

INSERT INTO parametros_sistema (codigo, valor_numero, descripcion)
VALUES ('MONTO_APROBACION_ESPECIAL', 500000, 'Monto desde el cual una solicitud requiere aprobacion especial');

INSERT INTO usuarios (nombre_completo, correo, password_hash, id_departamento, telefono, puesto, estado)
VALUES ('Laura Rojas', 'laura@empresa.com', 'HASH_SIMULADO_123', 1, '8888-1111', 'Analista de Sistemas', 'ACTIVO');

INSERT INTO usuarios (nombre_completo, correo, password_hash, id_departamento, telefono, puesto, estado)
VALUES ('Carlos Mendez', 'carlos@empresa.com', 'HASH_SIMULADO_456', 2, '8888-2222', 'Contador', 'ACTIVO');

INSERT INTO usuarios (nombre_completo, correo, password_hash, id_departamento, telefono, puesto, estado)
VALUES ('Maria Fernandez', 'maria@empresa.com', 'HASH_SIMULADO_789', 1, '8888-3333', 'Jefatura de Tecnologia', 'ACTIVO');

INSERT INTO usuarios (nombre_completo, correo, password_hash, id_departamento, telefono, puesto, estado)
VALUES ('Roberto Vargas', 'roberto@empresa.com', 'HASH_SIMULADO_ABC', 3, '8888-4444', 'Auditor Interno', 'ACTIVO');

INSERT INTO usuarios (nombre_completo, correo, password_hash, id_departamento, telefono, puesto, estado)
VALUES ('Admin SIGESCOM', 'admin@sigescom.com', 'HASH_ADMIN_001', 1, '8888-0000', 'Administrador del Sistema', 'ACTIVO');

INSERT INTO usuario_rol (id_usuario, id_rol) VALUES (1, 2);
INSERT INTO usuario_rol (id_usuario, id_rol) VALUES (2, 2);
INSERT INTO usuario_rol (id_usuario, id_rol) VALUES (3, 3);
INSERT INTO usuario_rol (id_usuario, id_rol) VALUES (3, 2);
INSERT INTO usuario_rol (id_usuario, id_rol) VALUES (4, 4);
INSERT INTO usuario_rol (id_usuario, id_rol) VALUES (5, 1);

INSERT INTO reset_password (id_usuario, codigo_reset, fecha_expiracion, usado, ip_solicitud, user_agent)
VALUES (1, 'RESET-LAURA-2026', SYSDATE + (30 / 1440), 'N', '192.168.1.10', 'Postman');

INSERT INTO reset_password (id_usuario, codigo_reset, fecha_expiracion, usado, ip_solicitud, user_agent)
VALUES (2, 'RESET-CARLOS-2026', SYSDATE + (30 / 1440), 'N', '192.168.1.11', 'Postman');

INSERT INTO reset_password (id_usuario, codigo_reset, fecha_expiracion, fecha_uso, usado, ip_solicitud, user_agent)
VALUES (4, 'RESET-ROBERTO-USADO', SYSDATE + (30 / 1440), SYSDATE, 'S', '192.168.1.12', 'Postman');

COMMIT;
